apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "4222"
        config.linkerd.io/proxy-cpu-request: 50m
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: image
          image: busybox
          command:
            - /app/servicebin
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 5
          livenessProbe:
            exec:
              command:
                - /app/grpc_health_probe
                - -addr=:8080
          readinessProbe:
            exec:
              command:
                - /app/grpc_health_probe
                - -addr=:8080
          ports:
            - containerPort: 8080
              name: grpc
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 70m
            limits:
              cpu: "1"
              memory: 140Mi
          env:
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: grpc
            - name: S3_ALIAS
              valueFrom:
                configMapKeyRef:
                  key: alias
                  name: s3
            - name: S3_IMAGEBUCKETNAME
              valueFrom:
                configMapKeyRef:
                  key: imagebucketname
                  name: s3
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: endpoint
                  name: s3
            - name: S3_ACCESSKEYID
              valueFrom:
                configMapKeyRef:
                  key: accesskeyid
                  name: s3
            - name: S3_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: secretaccesskey
                  name: s3
            - name: S3_SECURE
              valueFrom:
                configMapKeyRef:
                  key: secure
                  name: s3
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: region
                  name: s3
            - name: LOGLEVEL
              value: error

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: image
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 500

---
apiVersion: v1
kind: Service
metadata:
  name: image
  labels:
    app: image
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: image
